function desiredTaskAcc = desiredTaskAcceleration(xCom,desiredComPosVelAcc,...
                                                  w_H_root,w_H_rootDes,...
                                                  w_H_l_sole,w_H_l_soleDes,...
                                                  w_H_r_sole,w_H_r_soleDes,taskVelocities,gainsPDCom,gain)

    desiredTaskAcc = zeros(18,1);
end