function [w_H_b, CoMDes,qDes,constraints,impedances,kpCom,kdCom,currentState,jointsSmoothingTime] = ...
          stateMachineWalking(CoM_0, q0, l_sole_CoM,r_sole_CoM,qj, t, ...
                              wrench_rightFoot,wrench_leftFoot,l_sole_H_b, r_sole_H_b, sm,gain,...
                              CoMDesInput, qjDesInput,constraintsInput,contactSwitch); 
    % still to be defined
    
end
